name: flutter_l10n
description: Simple cmd tools for Flutter localazitions. It can generate localazition codes from
  arb files by one cmd.
version: 0.1.3
author: chenenyu <ceychina@gmail.com>
homepage: https://github.com/chenenyu/flutter_l10n

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: "^1.6.2"
  args: "^1.5.2"
  logging: "^0.11.3+2"

#  intl: "^0.16.0"
